# Generated by Django 4.2.5 on 2023-09-26 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointstracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='pointstracking.school'),
        ),
    ]
