# Generated by Django 4.2.5 on 2023-09-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointstracking', '0002_grade_sort_order_alter_teacher_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='added_by',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
