# Generated by Django 4.2.5 on 2023-09-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointstracking', '0003_point_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='added_by',
            new_name='user',
        ),
    ]
