# Generated by Django 4.2.5 on 2023-09-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointstracking', '0005_quickspendpoints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuickSpendPoints',
            new_name='QuickSpendPoint',
        ),
    ]
